version: '3.3'

services: 
  nginx:
    image: christianseki/nginx:latest
    ports:
      - "80:80"
    deploy:
      mode: global
      restart_policy: 
        condition: on-failure
    networks:
      - public
networks:
  public:
    driver: overlay
    external: true
