version: '3'

services: 
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    deploy:
      mode: replicated
      restart_policy: 
        condition: on-failure
    networks:
      - public
networks:
  public:
    external:
      name: public