name: Deploy Infra
on:
  workflow_dispatch:
  push:
    branches: [master]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform-plan:
    name: Plan Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Terraform init
        run: cd aws && terraform init -input=false

      - name: Terraform validation
        run: cd aws && terraform validate

      - name: Terraform plan
        run: cd aws && terraform plan -input=false  

  deploy-terraform:
    name: Apply Terraform
    needs: terraform-plan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Terraform init
      run: cd aws && terraform init -input=false

    - name: Terraform validation
      run: cd aws && terraform validate

    - name: Terraform apply
      run: cd aws && terraform apply -auto-approve -input=false      
      
    - name: Sleep for 20s
      uses: juliangruber/sleep-action@v1
      with:
        time: 20s

    - name: generate secret cert for ansible
      run: |
          echo ${{ secrets.SWARM_MACHINES_KEY }} | base64 -d > ansible/swarm-machines.pem
          chmod 400 ansible/swarm-machines.pem
      shell: bash

    - name: run ansible playbook
      run: cd ansible && ansible-playbook main.yaml
